line_length:
  warning: 120
  error: 150
  ignores_comments: true

type_body_length:
  warning: 300
  error: 500

todo:
  severity: warning

force_cast:
  severity: error

identifier_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 40
    error: 50
  excluded:
    - i
    - id
    - url
    - vc
    - fd

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 40
    error: 50

trailing_newline:
  severity: warning

trailing_whitespace:
  severity: warning
  ignores_empty_lines: true
  ignores_comments: true

cyclomatic_complexity:
  warning: 10
  error: 15
  ignores_case_statements: true
